### ISSUE TITLE
Release version 2

### ISSUE THREAD

**Issue by rukai** [mdunsmuir/copy_dir#5]
It seems like the source in this repository is for a version 2 that has the walk_dir dependency removed. But that version has not been released to crates.io
This is an outdated dependency so its causing duplicates of walk_dir in my dep tree.
Releasing copy_dir version 2 would fix this.

Alternatively, given the inactivity, you might prefer to just mark the crate as unmaintained.

**Comment by mdunsmuir** [comment]
I am happy to take a look at updating the dependencies if the staleness is causing issues for some folks.

**Comment by rukai** [comment]
Would be much appreciated, thanks :)

**Comment by mdunsmuir** [comment]
Version 0.1.3 is pushed to crates.io with walkdir version bumped to "2" and some other extremely minor (no-op) housekeeping changes. I created the dependency-bump branch for this since the changes in master are more extensive and safely releasing them would take time I don't have right now.

I hope this dependency bump resolves the issue you were having with redundant dependencies in your build. Thanks for bringing it to my attention—I'm not actively working on this crate but I think it's useful as-is and I would like to keep it in a usable state.
